<#
.SYNOPSIS
    Generates an HTML report from Azure managed disk analysis JSON data.

.DESCRIPTION
    This script reads JSON output from azure-managed-disk-telemetry-analysis.ps1
    and generates a styled HTML report with interactive filtering, sorting, and
    color-coded recommendations.
    
    The HTML report features:
    - Summary statistics cards
    - Color-coded rows based on savings potential and efficiency
    - Interactive column sorting
    - Column-level filtering
    - CSV export of filtered results
    - Responsive design

.PARAMETER JsonPath
    Path to the JSON file containing disk analysis results.
    This is typically generated by azure-managed-disk-telemetry-analysis.ps1.

.PARAMETER OutputPath
    Optional path for the output HTML file. If not specified, generates a timestamped
    filename in the same directory as the JSON input.

.EXAMPLE
    .\New-DiskAnalysisHtmlReport.ps1 -JsonPath "disk-analysis-20250115-123456.json"
    
    Generates HTML report from the specified JSON file.

.EXAMPLE
    .\New-DiskAnalysisHtmlReport.ps1 -JsonPath "disk-analysis.json" -OutputPath "custom-report.html"
    
    Generates HTML report with custom output filename.

.NOTES
    Requires JSON file generated by azure-managed-disk-telemetry-analysis.ps1.
    The script dynamically adapts to the JSON structure, making it resilient to future changes.
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$JsonPath,
    
    [Parameter(Mandatory=$false)]
    [string]$OutputPath
)

# Validate JSON file exists
if (-not (Test-Path $JsonPath)) {
    throw "JSON file not found at: $JsonPath"
}

# Load and parse JSON data
Write-Host "Loading JSON data from: $JsonPath" -ForegroundColor Cyan
$jsonContent = Get-Content $JsonPath -Raw
$results = $jsonContent | ConvertFrom-Json

if (-not $results -or $results.Count -eq 0) {
    throw "No data found in JSON file or invalid format"
}

Write-Host "  Loaded $($results.Count) disk records" -ForegroundColor Green

# Determine output path if not specified
if (-not $OutputPath) {
    $jsonDir = Split-Path -Parent $JsonPath
    if (-not $jsonDir) { $jsonDir = (Get-Location).Path }
    $jsonBasename = [System.IO.Path]::GetFileNameWithoutExtension($JsonPath)
    $OutputPath = Join-Path $jsonDir "$jsonBasename.html"
}

Write-Host "Generating HTML report..." -ForegroundColor Cyan

# Generate HTML content
$html = @"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Azure Managed Disk Analysis Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
            min-height: 100vh;
        }
        
        .container {
            max-width: 100%;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            overflow: hidden;
        }
        
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        
        .header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }
        
        .header p {
            font-size: 1.1em;
            opacity: 0.9;
        }
        
        .stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            padding: 30px;
            background: #f8f9fa;
            border-bottom: 3px solid #e9ecef;
        }
        
        .stat-card {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            text-align: center;
        }
        
        .stat-card .number {
            font-size: 2.5em;
            font-weight: bold;
            color: #667eea;
            margin-bottom: 5px;
        }
        
        .stat-card .label {
            color: #6c757d;
            font-size: 0.9em;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        
        .legend {
            padding: 20px 30px;
            background: #fff3cd;
            border-bottom: 3px solid #ffc107;
        }
        
        .legend h3 {
            margin-bottom: 15px;
            color: #856404;
        }
        
        .legend-items {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
        }
        
        .legend-item {
            display: flex;
            align-items: center;
            gap: 10px;
        }
        
        .legend-color {
            width: 30px;
            height: 20px;
            border-radius: 4px;
            border: 1px solid #ddd;
        }
        
        .table-container {
            padding: 30px;
            overflow-x: auto;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.9em;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        
        thead {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            position: sticky;
            top: 0;
            z-index: 10;
        }
        
        th {
            padding: 15px 12px;
            text-align: left;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.85em;
            letter-spacing: 0.5px;
            cursor: pointer;
            user-select: none;
            position: relative;
        }
        
        th:hover {
            background: rgba(255,255,255,0.1);
        }
        
        th.sortable::after {
            content: ' ⇅';
            opacity: 0.3;
            font-size: 0.8em;
        }
        
        th.sort-asc::after {
            content: ' ▲';
            opacity: 1;
        }
        
        th.sort-desc::after {
            content: ' ▼';
            opacity: 1;
        }
        
        .filter-row {
            background: #f8f9fa;
        }
        
        .filter-row th {
            padding: 8px;
            cursor: default;
        }
        
        .filter-row th:hover {
            background: #f8f9fa;
        }
        
        .filter-input {
            width: 100%;
            padding: 6px 8px;
            border: 1px solid #ced4da;
            border-radius: 4px;
            font-size: 0.85em;
            font-family: 'Segoe UI', sans-serif;
        }
        
        .filter-input:focus {
            outline: none;
            border-color: #667eea;
            box-shadow: 0 0 0 2px rgba(102, 126, 234, 0.2);
        }
        
        .filter-controls {
            padding: 15px 30px;
            background: #f8f9fa;
            border-bottom: 2px solid #dee2e6;
            display: flex;
            gap: 15px;
            align-items: center;
            flex-wrap: wrap;
        }
        
        .filter-controls button {
            padding: 8px 16px;
            border: none;
            border-radius: 4px;
            background: #667eea;
            color: white;
            cursor: pointer;
            font-size: 0.9em;
            font-weight: 600;
            transition: background 0.2s;
        }
        
        .filter-controls button:hover {
            background: #5568d3;
        }
        
        .filter-controls .results-count {
            margin-left: auto;
            color: #6c757d;
            font-weight: 600;
        }
        
        td {
            padding: 12px;
            border-bottom: 1px solid #e9ecef;
        }
        
        tbody tr {
            transition: all 0.2s ease;
        }
        
        tbody tr:hover {
            transform: scale(1.01);
            box-shadow: 0 2px 8px rgba(0,0,0,0.2);
            filter: brightness(1.05);
        }
        
        /* Row highlighting based on status */
        .savings-critical {
            background: #ff6b6b !important;
            border-left: 4px solid #c92a2a;
            color: #fff;
        }
        
        .savings-critical td {
            color: #fff;
        }
        
        .savings-critical .badge {
            filter: brightness(1.1);
        }
        
        .savings-high {
            background: #ffcccc !important;
            border-left: 4px solid #e74c3c;
            color: #2c1a1a;
        }
        
        .savings-medium {
            background: #fff9db !important;
            border-left: 4px solid #f1c40f;
            color: #2c2416;
        }
        
        .inefficient-size {
            background: #ffe5cc !important;
            border-left: 4px solid #e67e22;
            color: #2c1f16;
        }
        
        .stay-ok {
            background: #d4edda !important;
            border-left: 4px solid #28a745;
            color: #1e4620;
        }
        
        .upgrade-needed {
            background: #fff3cd !important;
            border-left: 4px solid #ffc107;
            color: #2c2416;
        }
        
        .downgrade-opportunity {
            background: #d1ecf1 !important;
            border-left: 4px solid #17a2b8;
            color: #1a3e47;
        }
        
        .custom-size {
            background: #e7e8ff !important;
            border-left: 4px solid #6c5ce7;
            color: #2c2647;
        }
        
        .tier-not-handled {
            background: #f0f0f0 !important;
            border-left: 4px solid #95a5a6;
            color: #2c3e50;
        }
        
        .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.85em;
            font-weight: 600;
        }
        
        .badge-warning {
            background: #ffc107;
            color: #856404;
        }
        
        .badge-info {
            background: #17a2b8;
            color: white;
        }
        
        .badge-danger {
            background: #dc3545;
            color: white;
        }
        
        .badge-success {
            background: #28a745;
            color: white;
        }
        
        .badge-secondary {
            background: #6c757d;
            color: white;
        }
        
        .badge-purple {
            background: #6c5ce7;
            color: white;
        }
        
        .footer {
            padding: 20px;
            text-align: center;
            background: #f8f9fa;
            color: #6c757d;
            font-size: 0.9em;
        }
        
        .number-cell {
            text-align: right;
            font-family: 'Courier New', monospace;
        }
        
        .percent-high {
            color: #dc3545;
            font-weight: bold;
        }
        
        .percent-medium {
            color: #ffc107;
            font-weight: bold;
        }
        
        .percent-low {
            color: #28a745;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔍 Azure Managed Disk Analysis</h1>
            <p>Generated on $(Get-Date -Format "MMMM dd, yyyy 'at' HH:mm:ss")</p>
            <p style="font-size: 0.9em; margin-top: 10px;">Source: $([System.IO.Path]::GetFileName($JsonPath))</p>
        </div>

"@

# Calculate statistics
$totalDisks = $results.Count
$stayCount = ($results | Where-Object { $_.Decision -eq "Stay" -or $_.Decision -eq "Stay (latency-sensitive)" -or $_.Decision -eq "Stay (OS disk)" -or $_.Decision -eq "Stay (minimal savings)" }).Count

# Calculate savings categories
$criticalSavings = 0
$highSavings = 0
$mediumSavings = 0
$inefficientCount = 0

foreach ($result in $results) {
    $potentialSavings = 0
    if ($result.Decision -like "*Upgrade*Premium*" -or $result.Decision -like "*Downgrade*") {
        if ($result.CostDiffSSDtoBestPremium -lt 0) {
            $potentialSavings = [math]::Abs($result.CostDiffSSDtoBestPremium)
        } elseif ($result.CostSavingsHDDtoSSD -gt 0) {
            $potentialSavings = $result.CostSavingsHDDtoSSD
        }
    }
    
    if ($potentialSavings -gt 100) { $criticalSavings++ }
    elseif ($potentialSavings -gt 25) { $highSavings++ }
    elseif ($potentialSavings -gt 0) { $mediumSavings++ }
    
    # Check inefficiency (within 20% of lower tier)
    if ($result.BillingTier -ne "N/A" -and $result.BillingTier -ne "Custom" -and $result.CustomSize -eq "Yes") {
        $tierBoundaries = @(4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768)
        $currentTierIndex = $tierBoundaries.IndexOf([int]$result.BilledSizeGiB)
        if ($currentTierIndex -gt 0) {
            $lowerTierSize = $tierBoundaries[$currentTierIndex - 1]
            $threshold = $lowerTierSize * 1.2
            if ($result.ActualSizeGiB -le $threshold) {
                $inefficientCount++
            }
        }
    }
}

$html += @"
        <div class="stats">
            <div class="stat-card">
                <div class="number">$totalDisks</div>
                <div class="label">Total Disks</div>
            </div>
            <div class="stat-card">
                <div class="number" style="color: #ff6b6b;">$criticalSavings</div>
                <div class="label">Critical Savings (>`$100/mo)</div>
            </div>
            <div class="stat-card">
                <div class="number" style="color: #e74c3c;">$highSavings</div>
                <div class="label">High Savings (`$25-`$100/mo)</div>
            </div>
            <div class="stat-card">
                <div class="number" style="color: #f1c40f;">$mediumSavings</div>
                <div class="label">Medium Savings (<`$25/mo)</div>
            </div>
            <div class="stat-card">
                <div class="number" style="color: #e67e22;">$inefficientCount</div>
                <div class="label">Inefficient Sizing</div>
            </div>
            <div class="stat-card">
                <div class="number" style="color: #28a745;">$stayCount</div>
                <div class="label">Optimal</div>
            </div>
        </div>
        
        <div class="legend">
            <h3>📋 Row Color Legend</h3>
            <div class="legend-items">
                <div class="legend-item">
                    <div class="legend-color" style="background: #ff6b6b; border-left: 4px solid #c92a2a;"></div>
                    <span><strong>Critical Savings</strong> - Potential savings >`$100/month</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background: #ffcccc; border-left: 4px solid #e74c3c;"></div>
                    <span><strong>High Savings</strong> - Potential savings `$25-`$100/month</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background: #fff9db; border-left: 4px solid #f1c40f;"></div>
                    <span><strong>Medium Savings</strong> - Potential savings <`$25/month</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background: #ffe5cc; border-left: 4px solid #e67e22;"></div>
                    <span><strong>Inefficient/Needs Review</strong> - Within 20% of lower tier (wasting money)</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background: #d4edda; border-left: 4px solid #28a745;"></div>
                    <span><strong>Stay</strong> - Disk is optimally sized</span>
                </div>
            </div>
        </div>
        
        <div class="filter-controls">
            <button onclick="clearAllFilters()">Clear Filters</button>
            <button onclick="exportToCSV()">Export Filtered to CSV</button>
            <span class="results-count">Showing <span id="visibleCount">0</span> of <span id="totalCount">0</span> disks</span>
        </div>
        
        <div class="table-container">
            <table id="diskTable">
                <thead>
                    <tr>
                        <th class="sortable" onclick="sortTable(0)">Disk Name</th>
                        <th class="sortable" onclick="sortTable(1)">Resource Group</th>
                        <th class="sortable" onclick="sortTable(2)">SKU</th>
                        <th class="sortable" onclick="sortTable(3)">Actual Size</th>
                        <th class="sortable" onclick="sortTable(4)">Billed Size</th>
                        <th class="sortable" onclick="sortTable(5)">Tier</th>
                        <th class="sortable" onclick="sortTable(6)">Custom</th>
                        <th class="sortable" onclick="sortTable(7)">Metrics</th>
                        <th class="sortable" onclick="sortTable(8)">IOPS Above %</th>
                        <th class="sortable" onclick="sortTable(9)">MBps Above %</th>
                        <th class="sortable" onclick="sortTable(10)">Avg Latency (ms)</th>
                        <th class="sortable" onclick="sortTable(11)">Transactions</th>
                        <th class="sortable" onclick="sortTable(12)">Cost Diff</th>
                        <th class="sortable" onclick="sortTable(13)">Decision</th>
                    </tr>
                    <tr class="filter-row">
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                        <th><input type="text" class="filter-input" placeholder="Filter..." onkeyup="filterTable()"></th>
                    </tr>
                </thead>
                <tbody>

"@

# Generate table rows dynamically from JSON data
foreach ($result in ($results | Sort-Object Subscription, ResourceGroup, Disk)) {
    # Determine row class based on conditions
    $rowClass = ""
    $isInefficient = $false
    
    # Calculate potential savings
    $potentialSavings = 0
    if ($result.Decision -like "*Upgrade*Premium*" -or $result.Decision -like "*Downgrade*") {
        if ($result.CostDiffSSDtoBestPremium -lt 0) {
            $potentialSavings = [math]::Abs($result.CostDiffSSDtoBestPremium)
        } elseif ($result.CostSavingsHDDtoSSD -gt 0) {
            $potentialSavings = $result.CostSavingsHDDtoSSD
        }
    }
    
    # Check inefficiency (within 20% of lower tier)
    if ($result.BillingTier -ne "N/A" -and $result.BillingTier -ne "Custom" -and $result.CustomSize -eq "Yes") {
        $tierBoundaries = @(4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768)
        $currentTierIndex = $tierBoundaries.IndexOf([int]$result.BilledSizeGiB)
        if ($currentTierIndex -gt 0) {
            $lowerTierSize = $tierBoundaries[$currentTierIndex - 1]
            $threshold = $lowerTierSize * 1.2
            if ($result.ActualSizeGiB -le $threshold) {
                $isInefficient = $true
                $rowClass = "inefficient-size"
            }
        }
    }
    
    # Assign row class based on priority
    if ($potentialSavings -gt 100) {
        $rowClass = "savings-critical"
    } elseif ($potentialSavings -gt 25) {
        $rowClass = "savings-high"
    } elseif ($potentialSavings -gt 0 -and $potentialSavings -le 25) {
        $rowClass = "savings-medium"
    } elseif ($isInefficient) {
        $rowClass = "inefficient-size"
    } elseif ($result.Decision -match "^Stay") {
        $rowClass = "stay-ok"
    } elseif ($result.Decision -like "*Upgrade*") {
        $rowClass = "upgrade-needed"
    } elseif ($result.Decision -like "*Downgrade*") {
        $rowClass = "downgrade-opportunity"
    } elseif ($result.Decision -eq "Tier not handled") {
        $rowClass = "tier-not-handled"
    } elseif ($result.CustomSize -eq "Yes" -and $rowClass -eq "") {
        $rowClass = "custom-size"
    }
    
    # Format percentages with color
    $iopsClass = if ($result.PercentIOPSAbove -gt 5) { "percent-high" } elseif ($result.PercentIOPSAbove -gt 1) { "percent-medium" } else { "percent-low" }
    $mbpsClass = if ($result.PercentMBpsAbove -gt 5) { "percent-high" } elseif ($result.PercentMBpsAbove -gt 1) { "percent-medium" } else { "percent-low" }
    
    # Format latency
    if ($result.AvgLatencyMs -gt 0) {
        $latencyDisplay = "$($result.AvgLatencyMs) ms"
        $latencyClass = if ($result.AvgLatencyMs -gt 10) { "percent-high" } elseif ($result.AvgLatencyMs -gt 5) { "percent-medium" } else { "percent-low" }
    } else {
        $latencyDisplay = "-"
        $latencyClass = ""
    }
    
    # Create decision badge
    $decisionBadge = ""
    if ($result.Decision -like "*Upgrade*") {
        $decisionBadge = "<span class='badge badge-warning'>⬆️ $($result.Decision)</span>"
    } elseif ($result.Decision -like "*Downgrade*") {
        $decisionBadge = "<span class='badge badge-info'>⬇️ $($result.Decision)</span>"
    } elseif ($result.Decision -match "^Stay") {
        $decisionBadge = "<span class='badge badge-success'>✅ $($result.Decision)</span>"
    } elseif ($result.Decision -eq "Tier not handled") {
        $decisionBadge = "<span class='badge badge-secondary'>⚠️ $($result.Decision)</span>"
    } else {
        $decisionBadge = "<span class='badge badge-secondary'>$($result.Decision)</span>"
    }
    
    # Add inefficiency warning
    if ($isInefficient) {
        $decisionBadge = "<span class='badge badge-danger'>💸 Inefficient Size</span> " + $decisionBadge
    }
    
    # Custom size badge
    $customBadge = if ($result.CustomSize -eq "Yes") { "<span class='badge badge-purple'>Custom</span>" } else { "" }
    
    # Metrics status badge
    $metricsBadge = switch ($result.MetricsStatus) {
        "OK" { "<span class='badge badge-success'>✓</span>" }
        "Unattached" { "<span class='badge badge-secondary' title='Disk is not attached to any VM'>⚠️ Unattached</span>" }
        "No Metrics" { "<span class='badge badge-warning' title='VM may have been stopped during analysis period'>⚠️ No Data</span>" }
        default { "<span class='badge badge-secondary'>-</span>" }
    }
    
    # Cost difference display
    $costDiffDisplay = "-"
    $costDiffSortValue = 0
    $costDiffClass = ""
    
    if ($result.SKU -eq "StandardSSD_LRS" -and $result.Decision -like "*Premium*") {
        $costDiffSortValue = $result.CostDiffSSDtoBestPremium
        $absDiff = [math]::Abs($result.CostDiffSSDtoBestPremium)
        $premiumLabel = $result.BestPremiumOption
        
        if ($result.CostDiffSSDtoBestPremium -lt -5) {
            $costDiffClass = "percent-low"
            $costDiffDisplay = "<span class='badge badge-success'>$premiumLabel saves `$$($absDiff.ToString('F2'))</span>"
        } elseif ($result.CostDiffSSDtoBestPremium -lt 0) {
            $costDiffClass = "percent-low"
            $costDiffDisplay = "<span class='badge badge-info'>$premiumLabel saves `$$($absDiff.ToString('F2'))</span>"
        } elseif ($result.CostDiffSSDtoBestPremium -le 10) {
            $costDiffClass = "percent-medium"
            $costDiffDisplay = "<span class='badge badge-warning'>$premiumLabel +`$$($absDiff.ToString('F2'))</span>"
        } else {
            $costDiffClass = "percent-high"
            $costDiffDisplay = "<span class='badge badge-danger'>$premiumLabel +`$$($absDiff.ToString('F2'))</span>"
        }
    }
    elseif (($result.SKU -eq "Standard_LRS" -or $result.SKU -eq "StandardSSD_LRS" -or $result.Decision -like "*Downgrade*HDD*" -or $result.Decision -like "*Standard SSD*") -and $result.CostSavingsHDDtoSSD -ne 0) {
        $absDiff = [math]::Abs($result.CostSavingsHDDtoSSD)
        $costDiffSortValue = $result.CostSavingsHDDtoSSD
        
        if ($result.CostSavingsHDDtoSSD -gt 5) {
            $costDiffClass = "percent-high"
            $costDiffDisplay = "<span class='badge badge-danger'>HDD +`$$($absDiff.ToString('F2'))</span>"
        } elseif ($result.CostSavingsHDDtoSSD -gt 0) {
            $costDiffClass = "percent-medium"
            $costDiffDisplay = "<span class='badge badge-warning'>HDD +`$$($absDiff.ToString('F2'))</span>"
        } elseif ($result.CostSavingsHDDtoSSD -lt -5) {
            $costDiffClass = ""
            $costDiffDisplay = "<span class='badge badge-info'>SSD +`$$($absDiff.ToString('F2'))</span>"
        } else {
            $costDiffClass = ""
            $costDiffDisplay = "SSD +`$$($absDiff.ToString('F2'))"
        }
    }
    
    $html += @"
                    <tr class="$rowClass">
                        <td><strong>$($result.Disk)</strong></td>
                        <td>$($result.ResourceGroup)</td>
                        <td>$($result.SKU)</td>
                        <td class="number-cell">$($result.ActualSizeGiB) GiB</td>
                        <td class="number-cell">$($result.BilledSizeGiB) GiB</td>
                        <td>$($result.BillingTier)</td>
                        <td>$customBadge</td>
                        <td>$metricsBadge</td>
                        <td class="number-cell $iopsClass">$($result.PercentIOPSAbove)%</td>
                        <td class="number-cell $mbpsClass">$($result.PercentMBpsAbove)%</td>
                        <td class="number-cell $latencyClass">$latencyDisplay</td>
                        <td class="number-cell">$([math]::Round($result.Transactions, 0).ToString("N0"))</td>
                        <td class="number-cell $costDiffClass" data-sort-value="$costDiffSortValue">$costDiffDisplay</td>
                        <td>$decisionBadge</td>
                    </tr>

"@
}

$html += @"
                </tbody>
            </table>
        </div>
        
        <div class="footer">
            <p>Azure Managed Disk Analysis Report | Generated by Emergent Software</p>
            <p>Source: $([System.IO.Path]::GetFileName($JsonPath))</p>
        </div>
    </div>
    
    <script>
        // Initialize counts on page load
        window.addEventListener('DOMContentLoaded', function() {
            updateCount();
        });
        
        // Sort table by column
        let sortDirection = {};
        function sortTable(columnIndex) {
            const table = document.getElementById('diskTable');
            const tbody = table.tBodies[0];
            const rows = Array.from(tbody.rows);
            
            // Toggle sort direction
            if (!sortDirection[columnIndex]) sortDirection[columnIndex] = 'asc';
            else sortDirection[columnIndex] = sortDirection[columnIndex] === 'asc' ? 'desc' : 'asc';
            
            const isAscending = sortDirection[columnIndex] === 'asc';
            
            // Remove sort indicators from all headers
            const headers = table.querySelectorAll('thead tr:first-child th');
            headers.forEach(th => {
                th.classList.remove('sort-asc', 'sort-desc');
            });
            
            // Add sort indicator to current header
            headers[columnIndex].classList.add(isAscending ? 'sort-asc' : 'sort-desc');
            
            // Sort rows
            rows.sort((a, b) => {
                let aValue = a.cells[columnIndex].textContent.trim();
                let bValue = b.cells[columnIndex].textContent.trim();
                
                // Check for data-sort-value attribute
                const aSortAttr = a.cells[columnIndex].getAttribute('data-sort-value');
                const bSortAttr = b.cells[columnIndex].getAttribute('data-sort-value');
                
                if (aSortAttr !== null && bSortAttr !== null) {
                    const aNum = parseFloat(aSortAttr);
                    const bNum = parseFloat(bSortAttr);
                    return isAscending ? aNum - bNum : bNum - aNum;
                }
                
                // Remove common formatting for numeric comparison
                aValue = aValue.replace(/[,$%]/g, '').replace(' GiB', '');
                bValue = bValue.replace(/[,$%]/g, '').replace(' GiB', '');
                
                // Try numeric comparison
                const aNum = parseFloat(aValue);
                const bNum = parseFloat(bValue);
                
                if (!isNaN(aNum) && !isNaN(bNum)) {
                    return isAscending ? aNum - bNum : bNum - aNum;
                }
                
                // Fall back to string comparison
                return isAscending ? 
                    aValue.localeCompare(bValue) : 
                    bValue.localeCompare(aValue);
            });
            
            // Reappend sorted rows
            rows.forEach(row => tbody.appendChild(row));
        }
        
        // Filter table based on all filter inputs
        function filterTable() {
            const table = document.getElementById('diskTable');
            const tbody = table.tBodies[0];
            const filterRow = table.querySelectorAll('.filter-row input');
            const filters = Array.from(filterRow).map(input => input.value.toLowerCase());
            
            let visibleCount = 0;
            
            Array.from(tbody.rows).forEach(row => {
                let showRow = true;
                
                filters.forEach((filter, index) => {
                    if (filter && row.cells[index]) {
                        const cellText = row.cells[index].textContent.toLowerCase();
                        if (!cellText.includes(filter)) {
                            showRow = false;
                        }
                    }
                });
                
                row.style.display = showRow ? '' : 'none';
                if (showRow) visibleCount++;
            });
            
            updateCount(visibleCount);
        }
        
        // Clear all filter inputs
        function clearAllFilters() {
            const filterInputs = document.querySelectorAll('.filter-input');
            filterInputs.forEach(input => input.value = '');
            filterTable();
        }
        
        // Update visible/total count
        function updateCount(visible) {
            const table = document.getElementById('diskTable');
            const tbody = table.tBodies[0];
            const total = tbody.rows.length;
            
            if (visible === undefined) {
                visible = Array.from(tbody.rows).filter(row => row.style.display !== 'none').length;
            }
            
            document.getElementById('visibleCount').textContent = visible;
            document.getElementById('totalCount').textContent = total;
        }
        
        // Export filtered results to CSV
        function exportToCSV() {
            const table = document.getElementById('diskTable');
            const headers = Array.from(table.querySelectorAll('thead tr:first-child th'))
                .map(th => th.textContent.trim().replace(/[⇅▲▼]/g, '').trim());
            
            const visibleRows = Array.from(table.tBodies[0].rows)
                .filter(row => row.style.display !== 'none');
            
            let csv = headers.map(h => '"' + h + '"').join(',') + '\\n';
            
            visibleRows.forEach(row => {
                const rowData = Array.from(row.cells).map(cell => {
                    let text = cell.textContent.trim();
                    // Remove emoji and extra whitespace
                    text = text.replace(/[🔍⬆️⬇️✅⚠️💸]/g, '').trim();
                    return '"' + text.replace(/"/g, '""') + '"';
                });
                csv += rowData.join(',') + '\\n';
            });
            
            // Download CSV
            const blob = new Blob([csv], { type: 'text/csv' });
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'disk-analysis-filtered-' + new Date().toISOString().slice(0,10) + '.csv';
            a.click();
            window.URL.revokeObjectURL(url);
        }
    </script>
</body>
</html>
"@

# Write HTML to file
$html | Set-Content -Path $OutputPath -Encoding UTF8

Write-Host "  HTML report generated: $OutputPath" -ForegroundColor Green
Write-Host "`n✅ Report generation complete!" -ForegroundColor Green
